#!/bin/bash

set -e

VERSION="1.0.1"
PROGNAME="$(basename "$0")"

usage() {
	cat<<EOF
$PROGNAME version $VERSION

Usage $PROGNAME [option]

Options:
    -V, --version	Show script version
    -h, --help		Show this help message

Example sudo $PROGNAME
	$PROGNAME -V

EOF
}

while [ $# -gt 0 ]; do
	case "$1" in
		-V|--version)
			echo "$PROGNAME version $VERSION"
			exit 0
			;;
		-h|--help)
			usage
			exit 0
			;;
	esac
done

BACKUP_ROOT="$HOME/backup"
MAX_BACKUPS=5
DATE=$(date +%Y-%m-%d_%H-%M-%S)
BACKUP_DIR="$BACKUP_ROOT/$DATE"
ARCHIVE_FILE="$BACKUP_ROOT/$DATE.tar.gz"

echo "[*] Creating backup in $BACKUP_DIR ..."
mkdir -p "$BACKUP_DIR"

echo "[*] Saving package list from pacman ..."
pacman -Qqe > "$BACKUP_DIR/pkglist.txt"

if command -v yay >/dev/null 2>&1; then
	echo "[*] Savin AUR pakage list from yay"
	yay -Qqe > "$BACKUP_DIR/aur_pkglist.txt"
elif command -v paru >/dev/null 2>&1; then
	echo "[*] Savin AUR pakage list from paur"
	paru -Qqe > "$BACKUP_DIR/aur_pkglist.txt"
else
	echo "[!] AUR-help not found"
fi

echo "[*] Copying configs from /etc"
rsync -aAX --exclude="*.cache" /etc/ "$BACKUP_DIR/etc"

echo "[*] Copying users configs"
rsync -aAX --ignore-missing-args --exclude="*.cache" --exclude="*/node_modules" "$HOME/.config" "$HOME/.bashrc" "$HOME/.zshrc" "$HOME/.profile" "$BACKUP_DIR/home_configs"

echo "[*] Saving system information"
uname -a > "$BACKUP_DIR/system_info.txt"

echo "[*] Backup archiving"
tar -czf "$ARCHIVE_FILE" -C "$BACKUP_ROOT" "$DATE"

echo "[*] Integrity checksum"
sha256sum "$ARCHIVE_FILE" > "$ARCHIVE_FILE.sha256"

echo "[*] Deleting old backups"
cd "$BACKUP_ROOT"
while [ $(ls -1 | grep -E '\.tar\.gz$' | wc -l) -gt $MAX_BACKUPS ]; do
	OLDEST=$(ls -1tr | grep -E '\.tar\.gz$' | head -n 1)
	rm -f "$OLDEST" "${OLDEST%.tar.gz}.sha256"
done

rm -rf "$BACKUP_DIR"

echo "Backup complete"
