#!/bin/bash

set -e

BACKUP_ROOT="$HOME/backup"
MAX_BACKUPS=5
DATE=$(date +%Y-%m-%d_%H-%M-%S)
BACKUP_DIR="$BACKUP_ROOT/$DATE"
ARCHIVE_FILE="$BACKUP_ROOT/$DATE.tar.gz"

echo "[*] Creating backup in $BACKUP_DIR ..."
mkdir -p "$BACKUP_DIR"

echo "[*] Saving package list from pacman ..."
pacman -Qqe > "$BACKUP_DIR/pkglist.txt"

if command -v yay >/dev/null 2>&1; then
	echo "[*] Savin AUR pakage list from yay"
	yay -Qqe > "$BACKUP_DIR/aur_pkglist.txt"
elif command -v paru >/dev/null 2>&1; then
	echo "[*] Savin AUR pakage list from paur"
	paru -Qqe > "$BACKUP_DIR/aur_pkglist.txt"
else
	echo "[!] AUR-help not found"
fi

echo "[*] Copying configs from /etc"
sudo rsync -aAX --exclude="*.cache" /etc/ "$BACKUP_DIR/etc"

echo "[*] Copying users configs"
sudo rsync -aAX --ignore-missing-args --exclude="*.cache" --exclude="*/node_modules" "$HOME/.config" "$HOME/.bashrc" "$HOME/.zshrc" "$HOME/.profile" "$BACKUP_DIR/home_configs"

echo "[*] Saving system information"
uname -a > "$BACKUP_DIR/system_info.txt"

echo "[*] Backup archiving"
sudo tar -czf "$ARCHIVE_FILE" -C "$BACKUP_ROOT" "$DATE"

echo "[*] Integrity checksum"
sha256sum "$ARCHIVE_FILE" > "$ARCHIVE_FILE.sha256"

echo "[*] Deleting old backups"
cd "$BACKUP_ROOT"
while [ $(ls -1 | grep -E '\.tar\.gz$' | wc -l) -gt $MAX_BACKUPS ]; do
	OLDEST=$(ls -1tr | grep -E '\.tar\.gz$' | head -n 1)
	sudo rm -f "$OLDEST" "${OLDEST%.tar.gz}.sha256"
done

sudo rm -rf "$BACKUP_DIR"

echo "Backup complete"
